# Generated by Django 5.2.10 on 2026-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notified",
            field=models.DateField(blank=True, null=True),
        ),
    ]
