# Generated by Django 5.2.10 on 2026-01-08 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_created_at_remove_habit_last_notified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["time"], "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AddField(
            model_name="habit",
            name="last_notified",
            field=models.DateField(blank=True, help_text="Дата последнего уведомления о привычке", null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(help_text="Действие, которое представляет привычку", max_length=255),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(help_text="Время выполнения привычки в секундах (≤ 120)"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1, help_text="Периодичность выполнения привычки в днях (от 1 до 7)"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default=False, help_text="Признак приятной привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(default=False, help_text="Привычка доступна в публичном списке"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(help_text="Место, где нужно выполнять привычку", max_length=255),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Связанная приятная привычка для полезной привычки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_to",
                to="habits.habit",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, help_text="Вознаграждение за выполнение полезной привычки", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(help_text="Время, когда необходимо выполнять привычку"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, создавший привычку",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
