# Generated by Django 5.2.10 on 2026-01-08 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Telegram профиль",
                "verbose_name_plural": "Telegram профили",
            },
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="chat_id",
            field=models.BigIntegerField(
                help_text="Уникальный идентификатор чата пользователя в Telegram",
                unique=True,
                verbose_name="Telegram chat ID",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Дата и время создания профиля"),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Пользователь, связанный с профилем Telegram",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
